# Generated by Django 4.0.3 on 2022-03-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioApp', '0002_remove_consulta_enviada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expediente',
        ),
    ]
