# Generated by Django 4.0.4 on 2022-05-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioApp', '0006_post_subtitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
