# Generated by Django 4.0.4 on 2022-06-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioApp', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
